In [2]:
# prepare the data from 3
import pandas as pd
strat_test_set = pd.read_csv("./strat_test_set")
strat_train_set= pd.read_csv("./strat_train_set")
# housing["rooms_per_household"]=housing["total_rooms"]/housing["households"]
# housing["bedrooms_per_room"]=housing["total_bedrooms"]/housing["total_rooms"]
# housing["population_per_household"]=housing["population"]/housing["households"]
strat_train_set.copy().count()

longitude             16512
latitude              16512
housing_median_age    16512
total_rooms           16512
total_bedrooms        16354
population            16512
households            16512
median_income         16512
median_house_value    16512
ocean_proximity       16512
dtype: int64

In [3]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()
# data cleaning
housing.count()

longitude             16512
latitude              16512
housing_median_age    16512
total_rooms           16512
total_bedrooms        16354
population            16512
households            16512
median_income         16512
ocean_proximity       16512
dtype: int64

In [4]:
sample_incomplete_rows = housing[housing.isnull().any(axis=1)].head()
sample_incomplete_rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
113    -118.30     34.07                18.0       3759.0             NaN   
116    -117.86     34.01                16.0       4632.0             NaN   
216    -121.97     37.35                30.0       1955.0             NaN   
303    -117.30     34.05                 6.0       2155.0             NaN   
321    -122.79     38.48                 7.0       6837.0             NaN   

     population  households  median_income ocean_proximity  
113      3296.0      1462.0         2.2708       <1H OCEAN  
116      3038.0       727.0         5.1762       <1H OCEAN  
216       999.0       386.0         4.6328       <1H OCEAN  
303      1039.0       391.0         1.6675          INLAND  
321      3468.0      1405.0         3.1662       <1H OCEAN

In [5]:
# This is just sample
median = housing["total_bedrooms"].median()
sample_incomplete_rows["total_bedrooms"].fillna(median, inplace=True) # option 3
sample_incomplete_rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
113    -118.30     34.07                18.0       3759.0           433.0   
116    -117.86     34.01                16.0       4632.0           433.0   
216    -121.97     37.35                30.0       1955.0           433.0   
303    -117.30     34.05                 6.0       2155.0           433.0   
321    -122.79     38.48                 7.0       6837.0           433.0   

     population  households  median_income ocean_proximity  
113      3296.0      1462.0         2.2708       <1H OCEAN  
116      3038.0       727.0         5.1762       <1H OCEAN  
216       999.0       386.0         4.6328       <1H OCEAN  
303      1039.0       391.0         1.6675          INLAND  
321      3468.0      1405.0         3.1662       <1H OCEAN

In [6]:
try:
    from sklearn.impute import SimpleImputer
except ImportError:
    from sklearn.preprocessing import Imputer as SimpleImputer
    
imputer = SimpleImputer(strategy="median")

In [7]:
housing_num = housing.drop("ocean_proximity", axis=1)
imputer.fit(housing_num)

SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='median', verbose=0)

In [8]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [9]:
housing_num.median().values

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [10]:
X = imputer.transform(housing_num)

In [11]:
housing_tr = pd.DataFrame(X,
                          columns=housing_num.columns,
                          index=housing_num.index
                         )

In [12]:
# type(housing_tr)
housing_tr.loc[sample_incomplete_rows.index.values]
# The sample rows's total_bedrooms is Nan before.
# Now it is median 433.0
# housing_tr.head() 
# The index is diff from below, but it doesn't matter.

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
113    -118.30     34.07                18.0       3759.0           433.0   
116    -117.86     34.01                16.0       4632.0           433.0   
216    -121.97     37.35                30.0       1955.0           433.0   
303    -117.30     34.05                 6.0       2155.0           433.0   
321    -122.79     38.48                 7.0       6837.0           433.0   

     population  households  median_income  
113      3296.0      1462.0         2.2708  
116      3038.0       727.0         5.1762  
216       999.0       386.0         4.6328  
303      1039.0       391.0         1.6675  
321      3468.0      1405.0         3.1662

In [13]:
imputer.strategy

'median'

In [14]:
housing_tr = pd.DataFrame(X,
                          columns=housing_num.columns,
                          index=housing_num.index)
housing_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income  
0       710.0       339.0         2.7042  
1       306.0       113.0         6.4214  
2       936.0       462.0         2.8621  
3      1460.0       353.0         1.8839  
4      4459.0      1463.0         3.0347

In [15]:
# Let's preprocess the categorical input feature.
housing_cat = housing[['ocean_proximity']]
housing_cat.head(10)

ocean_proximity
0       <1H OCEAN
1       <1H OCEAN
2      NEAR OCEAN
3          INLAND
4       <1H OCEAN
5          INLAND
6       <1H OCEAN
7          INLAND
8       <1H OCEAN
9       <1H OCEAN

In [16]:
try:
    from sklearn.preprocessing import OrdinalEncoder
except ImportError:
    from future_encoders import OrdinalEncoder

In [17]:
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded[:10]

array([[0.],
       [0.],
       [4.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [18]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [19]:
try:
    from sklearn.preprocessing import OrdinalEncoder # just to raise an ImportError if Scikit-Learn < 0.20
    from sklearn.preprocessing import OneHotEncoder
except ImportError:
    from future_encoders import OneHotEncoder # Scikit-Learn < 0.20

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot # It is a sparse array.

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [20]:
housing_cat_1hot.toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
cat_encoder = OneHotEncoder(sparse=False)
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [22]:
cat_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [23]:
housing.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [24]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
# get the right column indices:
# safer than hard-coding indices 3, 4, 5, 6
# 这几个列的索引组成的列表
# [list(housing.columns).index(col) for col in ("total_rooms", "total_bedrooms", "population", "households")]
rooms_ix, bedrooms_ix, population_ix, household_ix = [
    list(housing.columns).index(col) 
    for col in ("total_rooms", "total_bedrooms", "population", "households")
]

class CombineAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, population_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, population_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombineAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [25]:
# housing.values

In [26]:
from sklearn.preprocessing import FunctionTransformer

def add_extra_features(X, add_bedrooms_per_room=True):
    rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
    population_per_household = X[:, population_ix] / X[:, household_ix]
    if add_bedrooms_per_room:
        bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
        return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
    else:
        return np.c_[X, rooms_per_household, population_per_household]

attr_adder = FunctionTransformer(add_extra_features, validate=False, kw_args={"add_bedrooms_per_room": False})

housing_extra_attribs = attr_adder.fit_transform(housing.values)

In [27]:
housing_extra_attribs = pd.DataFrame(
    housing_extra_attribs,
    columns=list(housing.columns)+["rooms_per_household", "population_per_household"],
    index=housing.index
)
housing_extra_attribs.head()

longitude latitude housing_median_age total_rooms total_bedrooms population  \
0   -121.89    37.29                 38        1568            351        710   
1   -121.93    37.05                 14         679            108        306   
2    -117.2    32.77                 31        1952            471        936   
3   -119.61    36.31                 25        1847            371       1460   
4   -118.59    34.23                 17        6592           1525       4459   

  households median_income ocean_proximity rooms_per_household  \
0        339        2.7042       <1H OCEAN             4.62537   
1        113        6.4214       <1H OCEAN             6.00885   
2        462        2.8621      NEAR OCEAN             4.22511   
3        353        1.8839          INLAND             5.23229   
4       1463        3.0347       <1H OCEAN             4.50581   

  population_per_household  
0                   2.0944  
1                  2.70796  
2                  2.02597  
3                  4.13598  
4                  3.04785

In [28]:
# Build a pipeline for preprocessing the numerical attributes
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('attr_adder', FunctionTransformer(add_extra_features, validate=False)),
    ('std_scaler', StandardScaler()),
])

housing_num_tr = num_pipeline.fit_transform(housing_num)

In [29]:
housing_num_tr

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.31205452,
        -0.08649871,  0.15531753],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.21768338,
        -0.03353391, -0.83628902],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.46531516,
        -0.09240499,  0.4222004 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.3469342 ,
        -0.03055414, -0.52177644],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.02499488,
         0.06150916, -0.30340741],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.22852947,
        -0.09586294,  0.10180567]])

In [30]:
try:
    from sklearn.compose import ColumnTransformer
except ImportError:
    from future_encoders import ColumnTransformer # Scikit-Learn < 0.20

In [31]:
# type(list(housing_num))
# type(housing_num)

In [32]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", OneHotEncoder(), cat_attribs),
])
housing_prepared = full_pipeline.fit_transform(housing)

In [33]:
housing_prepared

array([[-1.15604281,  0.77194962,  0.74333089, ...,  0.        ,
         0.        ,  0.        ],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.18684903, -1.34218285,  0.18664186, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.        ,
         1.        ,  0.        ]])

In [34]:
housing_prepared.shape

(16512, 16)

In [35]:
from sklearn.base import BaseEstimator, TransformerMixin
# Create a class to select numrical or categorical columns
class OldDataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [36]:
try:
    from sklearn.preprocessing import OrdinalEncoder # just to raise an ImportError if Scikit-Learn < 0.20
    from sklearn.preprocessing import OneHotEncoder
except ImportError:
    from future_encoders import OneHotEncoder # Scikit-Learn < 0.20

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

old_num_pipeline = Pipeline([
    ('selector', OldDataFrameSelector(num_attribs)),
    ('imputer', SimpleImputer(strategy="median")),
    ('attr_adder', FunctionTransformer(add_extra_features, validate=False)),
    ('std_scaler', StandardScaler()),
])

old_cat_pipeline = Pipeline([
    ('selector', OldDataFrameSelector(cat_attribs)),
    ('cat_encoder', OneHotEncoder(sparse=False))
])

In [37]:
from sklearn.pipeline import FeatureUnion

old_full_pipeline = FeatureUnion(transformer_list=[
    ('num_pipeline', old_num_pipeline),
    ('cat_pipeline', old_cat_pipeline),
])

In [38]:
old_housing_prepared = old_full_pipeline.fit_transform(housing)
old_housing_prepared

array([[-1.15604281,  0.77194962,  0.74333089, ...,  0.        ,
         0.        ,  0.        ],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.18684903, -1.34218285,  0.18664186, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.        ,
         1.        ,  0.        ]])

In [39]:
# The result is the same as with the ColumnTransformer:
np.allclose(housing_prepared, old_housing_prepared)

True

## Select and Train a Modal

In [40]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [41]:
# Lets's try it out on a few instances from the training set:
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)
# print(some_data_prepared)
some_data_prepared.shape

(5, 16)

In [42]:
print("Prediction:\t", lin_reg.predict(some_data_prepared))

Prediction:	 [210644.60459286 317768.80697211 210956.43331178  59218.98886849
 189747.55849879]


In [43]:
print("Label:\t", list(housing_labels.iloc[:5]))

Label:	 [286600.0, 340600.0, 196900.0, 46300.0, 254500.0]


In [44]:
# Let's measure this regression model's RMSE 
# on the whole training set using Scikit-Learn's mean_squared_error funcion
from sklearn.metrics import mean_squared_error
housing_predictons = lin_reg.predict(housing_prepared)
lin_mse = mean_squared_error(housing_labels, housing_predictons)
lin_rmse = np.sqrt(lin_mse)
lin_rmse
# It can mean that the features do not provide enough information to make good predictions,
# or that the model is not powerful enough.

68628.19819848923

In [45]:
# DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(housing_prepared, housing_labels)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [46]:
housing_predictons = tree_reg.predict(housing_prepared)
tree_mse = mean_squared_error(housing_labels, housing_predictons)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.0

# Better Evaluation Using Cross-Validation

In [47]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree_reg, housing_prepared, housing_labels,
                        scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)

In [48]:
def dispaly_scores(scores):
    print("Scores", scores)
    print("Mean", scores.mean())
    print("Standard deviation", scores.std())

In [49]:
dispaly_scores(tree_rmse_scores)

Scores [68482.46337912 67455.42803296 70149.42402046 68778.35209348
 69570.16619059 74932.85136042 70546.41743907 71834.65449377
 76665.52179609 69022.76956655]
Mean 70743.8048372509
Standard deviation 2798.6876851224138


In [50]:
lin_scores = cross_val_score(lin_reg, housing_prepared, housing_labels,
                        scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
dispaly_scores(lin_rmse_scores)
# The Dission Tree model is overfitting so badly that it performs wores
# than the Linear Ressgression model.

Scores [66782.73843989 66960.118071   70347.95244419 74739.57052552
 68031.13388938 71193.84183426 64969.63056405 68281.61137997
 71552.91566558 67665.10082067]
Mean 69052.46136345083
Standard deviation 2731.6740017983457


In [51]:
# RandowForestRegressor
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor(n_estimators=10, random_state=42)
forest_reg.fit(housing_prepared, housing_labels)
forest_scores = cross_val_score(forest_reg, housing_prepared, housing_labels,
                        scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
dispaly_scores(forest_rmse_scores)

Scores [51646.44545909 48940.60114882 53050.86323649 54408.98730149
 50922.14870785 56482.50703987 51864.52025526 49760.85037653
 55434.21627933 53326.10093303]
Mean 52583.72407377466
Standard deviation 2298.353351147122


In [52]:
# Grid Search
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'n_estimators': [3, 10, 30], 'max_features': [2 ,4, 6, 8]},
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2 ,3, 4]},
]

forest_reg = RandomForestRegressor()
grid_search = GridSearchCV(forest_reg, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(housing_prepared, housing_labels)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid=[{'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]}, {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [54]:
grid_search.best_params_

{'max_features': 8, 'n_estimators': 30}

In [57]:
cvrers = grid_search.cv_results_
for mean_score, params in zip(cvers["mean_test_score"], cvrers["params"]):
    print(np.sqrt(-mean_score), params)

65141.64232084479 {'max_features': 2, 'n_estimators': 3}
55557.11357918827 {'max_features': 2, 'n_estimators': 10}
52599.08085422682 {'max_features': 2, 'n_estimators': 30}
60369.37131434058 {'max_features': 4, 'n_estimators': 3}
53336.428559059146 {'max_features': 4, 'n_estimators': 10}
50523.612872324535 {'max_features': 4, 'n_estimators': 30}
59475.103839990246 {'max_features': 6, 'n_estimators': 3}
52221.35462245736 {'max_features': 6, 'n_estimators': 10}
49783.66771329474 {'max_features': 6, 'n_estimators': 30}
58829.17196962166 {'max_features': 8, 'n_estimators': 3}
52206.22662521026 {'max_features': 8, 'n_estimators': 10}
49687.14308659769 {'max_features': 8, 'n_estimators': 30}
62529.54028453775 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
54212.368286972094 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
59094.24747628216 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
52990.237429762215 {'bootstrap': False, 'max_features': 3, 'n_estimators

In [58]:
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

array([6.88563953e-02, 6.59510483e-02, 4.33169866e-02, 1.54088757e-02,
       1.50547237e-02, 1.45536081e-02, 1.44837464e-02, 3.22612954e-01,
       5.93463978e-02, 1.18090034e-01, 8.23358856e-02, 5.89885189e-03,
       1.69715384e-01, 4.52025208e-05, 1.56981254e-03, 2.76009441e-03])

In [59]:
'''
extra_attribs = ["rooms_per_hhold", "pop_per_hhold", "bedrooms_per_room"]
cat_one_hot_attribs = list(encoder.classer_)
attributes = num_attribs + extra_attribs + cat_one_hot_attribs
sorted(zip(feature_importances, attributes), reverse=True)
'''

NameError: name 'encoder' is not defined

In [62]:
final_model = grid_search.best_estimator_

x_test = strat_test_set.drop("median_house_value", axis=1)
y_test = strat_test_set["median_house_value"].copy()

X_test_prepared = full_pipeline.transform(x_test)
final_predictions = final_model.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)

In [63]:
final_rmse

48224.33147405944